### ISSUE TITLE
Publishing Happens before Tests Finish

### ISSUE THREAD

**Issue by emclaug2** [etn-ccis/blui-angular-workflows#202]
#### Describe the bug
Cypress tests are ran after publishing and tagging of packages.

#### What is the expected behavior?
Package and tag steps should wait for the cypress tests job to finish before executing. 

#### What are the steps to reproduce?
1.  Go observe our latest master merge: https://app.circleci.com/pipelines/github/brightlayer-ui/angular-workflows/184/workflows/4ed0532e-f96a-4451-8271-f63e0ecfa3a0

#### Screenshots / Screen recording
![image](https://user-images.githubusercontent.com/6538289/203375654-ae8e801c-a3f5-45f1-9486-9e565bcc3d43.png)

**Comment by joebochill** [comment]
Need to add an extra dependency on the publish step so it runs after cypress_tests job finishes:
https://github.com/etn-ccis/blui-angular-workflows/blob/dev/.circleci/config.yml#L164
