### ISSUE TITLE
Use Waves SVG for Dark Theme

### ISSUE THREAD

**Issue by emclaug2** [etn-ccis/blui-angular-workflows#94]
#### Describe the bug
The create-account success page in the custom example is using an image that only looks good in the light theme.  React workflow example is using a waves svg that looks good in both light and dark, use that one here. 

#### What is the expected behavior?
The picture should look good on dark and light themes. 

#### What are the steps to reproduce?
1.  Clone the repo (`git clone https://github.com/brightlayer-ui/angular-workflows.git`).
2. CD into the project (`cd angular-workflows`)
3. Run the example project (`cd login-workflow && yarn start:example`)
4. Navigate to http://localhost:4200/auth/register/create-account
5. Inspect the page & update the `<body>` class from `blui-blue` to `blui-blue-dark`.  This will set the dark theme manually.
6. Fill in the required information to create an account.
7. Observe the final page; it should match the image below. 

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/6538289/120945065-aad85400-c705-11eb-98df-3f27a1456da7.png)

**Comment by joebochill** [comment]
The React Workflows don't have a waves image at all. The React Native ones do, but it looks like they are the same one that's used here (white background). We will need an updated graphic from @huayunh that has a transparent background that we can use for both light and dark theme.

**Comment by huayunh** [comment]
The no wave image is the default state:
<img width="668" alt="image" src="https://user-images.githubusercontent.com/8997218/228277545-9764e8a4-2694-4113-b135-cec71c4ebdec.png">

But we shall allow users to customize that area. For example, if you want to do the Eric Atha thing, you shall be allowed:

https://user-images.githubusercontent.com/8997218/228278651-fdc47105-9ffe-416e-bbdf-f992207e15cb.mov

**Comment by joebochill** [comment]
@huayunh understood — this fix is JUST in the example project, not in the main code...but we don't have the image asset that works well for light and dark theme (I don't see it anywhere in the react workflow repository even though it's mentioned in the description as being there, and the one in the RN repository has the same issue as reported here on angular). Do you have a wave image that uses a transparent background somewhere in Figma that we can use for this?

**Comment by huayunh** [comment]
[SVG](https://user-images.githubusercontent.com/8997218/228329266-878fcbae-8bb2-467f-8d9b-8895aa5fc8de.svg), [PNG](https://user-images.githubusercontent.com/8997218/228329263-0a244ae0-e86b-450d-a3bd-8b0753381ed4.png)
(Try SVG first)

Preview:
![image](https://user-images.githubusercontent.com/8997218/228329528-7f8c19be-9e52-4a25-aa19-d639fd4d86be.png)
