### ISSUE TITLE
Login Email input should have a consistant invalid email error message

### ISSUE THREAD

**Issue by daileytj** [etn-ccis/blui-angular-workflows#99]
#### Describe the bug
There is an error state but no error message when the input field is invalid but not active.
There is also no error message when the email is invalid but contains an `@` symbol.

#### What is the expected behavior?
The login email input should have an error message that says "Please enter a valid email" when the criteria for an email address is not met whether it's focused or not. 

#### What are the steps to reproduce?
1.  Clone the repo (`git clone https://github.com/brightlayer-ui/angular-workflows.git`).
2. CD into the project (`cd angular-workflows`)
3. Run the example project (`cd login-workflow && yarn start:example`)
4. Navigate to http://localhost:4200/auth/login
5. Type in the invalid email "asdfasd@dafasdf" and observe the lack of error.

#### Screenshots or links to minimum reproduction example
![Screen Shot 2021-06-24 at 2 02 52 PM](https://user-images.githubusercontent.com/13989985/123311235-f015c780-d4f4-11eb-893d-34b295dcabb2.png)
![Screen Shot 2021-06-24 at 2 04 09 PM](https://user-images.githubusercontent.com/13989985/123311345-1471a400-d4f5-11eb-9a9a-580fef0ddf96.png)

**Comment by joebochill** [comment]
This should mimic the updated behavior that was implemented in React (switching from verify on blur to onchange).

**Comment by joebochill** [comment]
If we update the description on this to be a little more explicit, we can mark it as a good first issue.
